[package]
name = "wowedit"
version = "0.1.0"
edition = "2021"

[features]
wgpu = ["eframe/wgpu"]

[dependencies]
puffin_egui = "0.27.0"
eframe = { version = "0.27.2", features = [
  "default",
  "puffin"
] }
egui = { version = "0.27.2", features = [
  "callstack",
  "default",
  "extra_debug_asserts",
  "log",
] }
puffin = "0.19"
bytes = "1.6.0"
anyhow = "1.0.82"
thiserror = "1.0.59"
md5 = "0.7.0"
enumflags2 = "0.7.9"